sequenceDiagram
  participant participant_normalizeManualRestDataSource as normalizeManualRestDataSource
  participant participant_normalizeManualRestMethod as normalizeManualRestMethod
  participant_normalizeManualRestDataSource->>participant_normalizeManualRestMethod: normalizeManualRestMethod()
  participant_normalizeManualRestMethod-->>participant_normalizeManualRestDataSource: return
