sequenceDiagram
  participant participant_normalizeGraphQlIntrospectionOperations as normalizeGraphQlIntrospectionOperations
  participant participant_normalizeRootOperations as normalizeRootOperations
  participant_normalizeGraphQlIntrospectionOperations->>participant_normalizeRootOperations: normalizeRootOperations()
  participant_normalizeRootOperations-->>participant_normalizeGraphQlIntrospectionOperations: return
