sequenceDiagram
  participant participant_normalizeGraphQlApi as normalizeGraphQlApi
  participant participant_normalizeGraphQlIntrospectionOperations as normalizeGraphQlIntrospectionOperations
  participant participant_normalizeGraphQlIntrospectionSchemas as normalizeGraphQlIntrospectionSchemas
  participant participant_normalizeRootOperations as normalizeRootOperations
  participant_normalizeGraphQlApi->>participant_normalizeGraphQlIntrospectionSchemas: normalizeGraphQlIntrospectionSchemas()
  participant_normalizeGraphQlIntrospectionSchemas-->>participant_normalizeGraphQlApi: return
  participant_normalizeGraphQlApi->>participant_normalizeGraphQlIntrospectionOperations: normalizeGraphQlIntrospectionOperations()
  participant_normalizeGraphQlIntrospectionOperations->>participant_normalizeRootOperations: normalizeRootOperations()
  participant_normalizeRootOperations-->>participant_normalizeGraphQlIntrospectionOperations: return
  participant_normalizeGraphQlIntrospectionOperations-->>participant_normalizeGraphQlApi: return
