graph TD
  package__ankhorage_data_sources["@ankhorage/data-sources"]
  entrypoint_src_index_ts["src/index.ts"]
  package__ankhorage_data_sources --> entrypoint_src_index_ts
  module_src_index_ts["src/index.ts"]
