graph TD
  package__ankhorage_data_sources["@ankhorage/data-sources"]
  entrypoint_src_index_ts["src/index.ts"]
  package__ankhorage_data_sources --> entrypoint_src_index_ts
  module_src_ankh_provider_ts["src/ankh.provider.ts"]
  package__ankhorage_data_sources -.-> module_src_ankh_provider_ts
  module_src_ankh_provider_ts --> module_src_index_ts
  module_src_graphql_index_ts["src/graphql/index.ts"]
  package__ankhorage_data_sources -.-> module_src_graphql_index_ts
  module_src_index_ts["src/index.ts"]
  module_src_managed_api_index_ts["src/managed-api/index.ts"]
  package__ankhorage_data_sources -.-> module_src_managed_api_index_ts
  module_src_openapi_index_ts["src/openapi/index.ts"]
  package__ankhorage_data_sources -.-> module_src_openapi_index_ts
  module_src_rest_index_ts["src/rest/index.ts"]
  package__ankhorage_data_sources -.-> module_src_rest_index_ts
  module_src_test_runner_index_ts["src/test-runner/index.ts"]
  package__ankhorage_data_sources -.-> module_src_test_runner_index_ts
