graph LR
  module_src_index_ts["src/index.ts"]
  module_src_openapi_index_ts["src/openapi/index.ts"]
  module_src_rest_index_ts["src/rest/index.ts"]
  module_src_index_ts -.-> module_src_openapi_index_ts
  module_src_openapi_index_ts -.-> module_src_rest_index_ts
